window.WINE_READINGS = Object.freeze({
  // France: regions, appellations, villages and vineyards
  "Appellation d'Origine Contrôlée": "アペラシオン・ドリジーヌ・コントロレ",
  "Indication Géographique Protégée": "アンディカシオン・ジェオグラフィック・プロテジェ",
  "Chambertin Clos-de-Bèze": "シャンベルタン・クロ・ド・ベーズ",
  "Bienvenues-Bâtard-Montrachet": "ビアンヴニュ・バタール・モンラッシェ",
  "Bâtard-Montrachet": "バタール・モンラッシェ",
  "Chevalier-Montrachet": "シュヴァリエ・モンラッシェ",
  "Criots-Bâtard-Montrachet": "クリオ・バタール・モンラッシェ",
  "Gevrey-Chambertin": "ジュヴレ・シャンベルタン",
  "Puligny-Montrachet": "ピュリニー・モンラッシェ",
  "Chassagne-Montrachet": "シャサーニュ・モンラッシェ",
  "Pernand-Vergelesses": "ペルナン・ヴェルジュレス",
  "Savigny-lès-Beaune": "サヴィニー・レ・ボーヌ",
  "Nuits-Saint-Georges": "ニュイ・サン・ジョルジュ",
  "Morey-Saint-Denis": "モレ・サン・ドニ",
  "Chambolle-Musigny": "シャンボール・ミュジニー",
  "Vosne-Romanée": "ヴォーヌ・ロマネ",
  "Flagey-Echézeaux": "フラジェ・エシェゾー",
  "Aloxe-Corton": "アロース・コルトン",
  "Auxey-Duresses": "オーセイ・デュレス",
  "Ladoix-Serrigny": "ラドワ・セリニー",
  "Romanée-Saint-Vivant": "ロマネ・サン・ヴィヴァン",
  "Romanée-Conti": "ロマネ・コンティ",
  "Grands Echézeaux": "グラン・エシェゾー",
  "Clos de la Roche": "クロ・ド・ラ・ロッシュ",
  "Clos Saint-Denis": "クロ・サン・ドニ",
  "Clos des Lambrays": "クロ・デ・ランブレ",
  "Clos de Vougeot": "クロ・ド・ヴージョ",
  "La Grande Rue": "ラ・グランド・リュ",
  "La Romanée": "ラ・ロマネ",
  "La Tâche": "ラ・ターシュ",
  "Bonnes-Mares": "ボンヌ・マール",
  "Charmes-Chambertin": "シャルム・シャンベルタン",
  "Chapelle-Chambertin": "シャペル・シャンベルタン",
  "Griotte-Chambertin": "グリオット・シャンベルタン",
  "Latricières-Chambertin": "ラトリシエール・シャンベルタン",
  "Mazis-Chambertin": "マジ・シャンベルタン",
  "Mazoyères-Chambertin": "マゾワイエール・シャンベルタン",
  "Corton-Charlemagne": "コルトン・シャルルマーニュ",
  "Echézeaux": "エシェゾー",
  "Richebourg": "リシュブール",
  "Musigny": "ミュジニー",
  "Montrachet": "モンラッシェ",
  "Chambertin": "シャンベルタン",
  "Corton": "コルトン",
  "Chablis": "シャブリ",
  "Marsannay": "マルサネ",
  "Fixin": "フィサン",
  "Vougeot": "ヴージョ",
  "Beaune": "ボーヌ",
  "Pommard": "ポマール",
  "Volnay": "ヴォルネイ",
  "Meursault": "ムルソー",
  "Monthélie": "モンテリー",
  "Mercurey": "メルキュレ",
  "Givry": "ジヴリ",
  "Rully": "リュリー",
  "Montagny": "モンタニー",
  "Pouilly-Fuissé": "プイィ・フュイッセ",
  "Pouilly-Vinzelles": "プイィ・ヴァンゼル",
  "Pouilly-Loché": "プイィ・ロシェ",
  "Viré-Clessé": "ヴィレ・クレッセ",
  "Saint-Véran": "サン・ヴェラン",
  "Bouzeron": "ブーズロン",
  "Mâcon-Villages": "マコン・ヴィラージュ",
  "Mâcon": "マコン",
  "Bourgogne Hautes-Côtes de Beaune": "ブルゴーニュ・オート・コート・ド・ボーヌ",
  "Bourgogne Hautes-Côtes de Nuits": "ブルゴーニュ・オート・コート・ド・ニュイ",
  "Bourgogne Aligoté": "ブルゴーニュ・アリゴテ",
  "Côte de Nuits": "コート・ド・ニュイ",
  "Côte de Beaune": "コート・ド・ボーヌ",
  "Côte Chalonnaise": "コート・シャロネーズ",
  "Mâconnais": "マコネ",
  "Bourgogne": "ブルゴーニュ",

  "Pessac-Léognan": "ペサック・レオニャン",
  "Saint-Émilion": "サン・テミリオン",
  "Montagne Saint-Émilion": "モンターニュ・サン・テミリオン",
  "Lussac Saint-Émilion": "リュサック・サン・テミリオン",
  "Puisseguin Saint-Émilion": "ピュイスガン・サン・テミリオン",
  "Saint-Georges Saint-Émilion": "サン・ジョルジュ・サン・テミリオン",
  "Lalande-de-Pomerol": "ラランド・ド・ポムロール",
  "Saint-Estèphe": "サン・テステフ",
  "Saint-Julien": "サン・ジュリアン",
  "Haut-Médoc": "オー・メドック",
  "Médoc": "メドック",
  "Pauillac": "ポイヤック",
  "Margaux": "マルゴー",
  "Moulis": "ムーリ",
  "Listrac-Médoc": "リストラック・メドック",
  "Graves": "グラーヴ",
  "Sauternes": "ソーテルヌ",
  "Barsac": "バルサック",
  "Cérons": "セロンス",
  "Pomerol": "ポムロール",
  "Fronsac": "フロンサック",
  "Canon-Fronsac": "カノン・フロンサック",
  "Entre-Deux-Mers": "アントル・ドゥー・メール",
  "Castillon Côtes de Bordeaux": "カスティヨン・コート・ド・ボルドー",
  "Francs Côtes de Bordeaux": "フラン・コート・ド・ボルドー",
  "Blaye Côtes de Bordeaux": "ブライ・コート・ド・ボルドー",
  "Cadillac Côtes de Bordeaux": "カディヤック・コート・ド・ボルドー",
  "Sainte-Foy Côtes de Bordeaux": "サント・フォワ・コート・ド・ボルドー",
  "Bordeaux Supérieur": "ボルドー・シュペリュール",
  "Bordeaux Rosé": "ボルドー・ロゼ",
  "Bordeaux Clairet": "ボルドー・クレレ",
  "Bordeaux": "ボルドー",

  "Le Mesnil-sur-Oger": "ル・メニル・シュール・オジェ",
  "Tours-sur-Marne": "トゥール・シュール・マルヌ",
  "Beaumont-sur-Vesle": "ボーモン・シュール・ヴェル",
  "Mailly-Champagne": "マイィ・シャンパーニュ",
  "Verzenay": "ヴェルズネ",
  "Verzy": "ヴェルジー",
  "Sillery": "シルリー",
  "Puisieulx": "ピュイジュー",
  "Louvois": "ルーヴォワ",
  "Bouzy": "ブージィ",
  "Ambonnay": "アンボネイ",
  "Aÿ": "アイ",
  "Avize": "アヴィーズ",
  "Cramant": "クラマン",
  "Chouilly": "シュイィ",
  "Oger": "オジェ",
  "Montagne de Reims": "モンターニュ・ド・ランス",
  "Vallée de la Marne": "ヴァレ・ド・ラ・マルヌ",
  "Côte des Blancs": "コート・デ・ブラン",
  "Côte des Bar": "コート・デ・バール",

  "Châteauneuf-du-Pape": "シャトーヌフ・デュ・パプ",
  "Crozes-Hermitage": "クローズ・エルミタージュ",
  "Côte-Rôtie": "コート・ロティ",
  "Château-Grillet": "シャトー・グリエ",
  "Saint-Joseph": "サン・ジョゼフ",
  "Saint-Péray": "サン・ペレイ",
  "Beaumes de Venise": "ボーム・ド・ヴニーズ",
  "Costières de Nîmes": "コスティエール・ド・ニーム",
  "Clairette de Die": "クレレット・ド・ディー",
  "Crémant de Die": "クレマン・ド・ディー",
  "Saint-Péray Mousseux": "サン・ペレイ・ムスー",
  "Muscat de Beaumes de Venise": "ミュスカ・ド・ボーム・ド・ヴニーズ",
  "Hermitage": "エルミタージュ",
  "Condrieu": "コンドリュー",
  "Cornas": "コルナス",
  "Gigondas": "ジゴンダス",
  "Vacqueyras": "ヴァケラス",
  "Vinsobres": "ヴァンソーブル",
  "Rasteau": "ラストー",
  "Cairanne": "ケランヌ",
  "Laudun": "ローダン",
  "Tavel": "タヴェル",
  "Lirac": "リラック",
  "Ventoux": "ヴァントゥー",
  "Luberon": "リュベロン",

  "Pouilly-Fumé": "プイィ・フュメ",
  "Muscadet": "ミュスカデ",
  "Sancerre": "サンセール",
  "Menetou-Salon": "メヌトゥー・サロン",
  "Quarts de Chaume": "カール・ド・ショーム",
  "Coteaux du Layon": "コトー・デュ・レイヨン",
  "Savennières": "サヴニエール",
  "Vouvray": "ヴーヴレ",
  "Chinon": "シノン",
  "Bourgueil": "ブルグイユ",
  "Saumur": "ソーミュール",
  "Anjou": "アンジュ",
  "Cour-Cheverny": "クール・シュヴェルニー",
  "Cheverny": "シュヴェルニー",
  "Côtes du Vivarais": "コート・デュ・ヴィヴァレ",
  "Châtillon-en-Diois": "シャティヨン・アン・ディオワ",
  "Duché d'Uzès": "デュシェ・デュゼス",
  "Coteaux de Die": "コトー・ド・ディー",
  "Grignan-les-Adhémar": "グリニャン・レ・ザデマール",
  "Beaujolais Villages": "ボージョレ・ヴィラージュ",
  "Beaujolais Supérieur": "ボージョレ・シュペリュール",
  "Beaujolais": "ボージョレ",
  "Côte de Brouilly": "コート・ド・ブルイィ",
  "Moulin-à-Vent": "ムーラン・ナ・ヴァン",
  "Saint-Amour": "サン・タムール",
  "Juliénas": "ジュリエナ",
  "Chénas": "シェナ",
  "Fleurie": "フルーリー",
  "Morgon": "モルゴン",
  "Régnié": "レニエ",
  "Brouilly": "ブルイィ",
  "Saint-Bris": "サン・ブリ",
  "Vézelay": "ヴェズレイ",
  "Irancy": "イランシー",
  "Cahors": "カオール",
  "Gaillac": "ガイヤック",
  "Fronton": "フロントン",
  "Madiran": "マディラン",
  "Irouléguy": "イルレギー",
  "Jurançon": "ジュランソン",
  "Banyuls": "バニュルス",
  "Collioure": "コリウール",
  "Maury": "モーリー",
  "Rivesaltes": "リヴザルト",
  "Bandol": "バンドール",
  "Bellet": "ベレ",
  "Cassis": "カシス",
  "Palette": "パレット",
  "Patrimonio": "パトリモニオ",
  "Ajaccio": "アジャクシオ",
  "Arbois": "アルボワ",
  "Château-Chalon": "シャトー・シャロン",
  "L'Étoile": "レトワール",
  "Côtes du Jura": "コート・デュ・ジュラ",
  "Crémant du Jura": "クレマン・デュ・ジュラ",
  "Château Doisy Daëne": "シャトー・ドワジ・デーヌ",
  "Château Smith-Haut-Lafitte": "シャトー・スミス・オー・ラフィット",
  "Château d'Arche": "シャトー・ダルシュ",
  "Château Lamothe": "シャトー・ラモット",
  "Entrecôte Bordelaise": "アントルコート・ボルドレーズ",
  "Tarte Flambée": "タルト・フランベ",
  "Touraine Blanc": "トゥーレーヌ・ブラン",
  "Alsace Riesling": "アルザス・リースリング",
  "Champagne Brut": "シャンパーニュ・ブリュット",
  "Grande Champagne": "グランド・シャンパーニュ",
  "Pont-l'Évêque": "ポン・レヴェック",
  "Selles-sur-Cher": "セル・シュール・シェール",
  "Neufchâtel": "ヌーシャテル",
  "Chavignol": "シャヴィニョル",
  "Valençay": "ヴァランセ",
  "Époisses": "エポワス",

  "Altenberg de Bergheim": "アルテンベルグ・ド・ベルガイム",
  "Kaefferkopf": "ケフェルコプフ",
  "Zotzenberg": "ゾッツェンベルグ",
  "Wiebelsberg": "ヴィーベルスベルグ",
  "Hengst": "ヘングスト",

  // French grape varieties
  "Cabernet Sauvignon": "カベルネ・ソーヴィニョン",
  "Cabernet Franc": "カベルネ・フラン",
  "Sauvignon Blanc": "ソーヴィニョン・ブラン",
  "Chenin Blanc": "シュナン・ブラン",
  "Pinot Noir": "ピノ・ノワール",
  "Pinot Gris": "ピノ・グリ",
  "Pinot Blanc": "ピノ・ブラン",
  "Petit Verdot": "プティ・ヴェルド",
  "Petit Manseng": "プティ・マンサン",
  "Gros Manseng": "グロ・マンサン",
  "Melon de Bourgogne": "ムロン・ド・ブルゴーニュ",
  "Gewürztraminer": "ゲヴュルツトラミネール",
  "Chardonnay": "シャルドネ",
  "Riesling": "リースリング",
  "Auxerrois": "オーセロワ",
  "Sylvaner": "シルヴァネール",
  "Aligoté": "アリゴテ",
  "Gamay": "ガメイ",
  "Merlot": "メルロ",
  "Malbec": "マルベック",
  "Carménère": "カルメネール",
  "Grenache": "グルナッシュ",
  "Syrah": "シラー",
  "Mourvèdre": "ムールヴェードル",
  "Cinsault": "サンソー",
  "Carignan": "カリニャン",
  "Viognier": "ヴィオニエ",
  "Marsanne": "マルサンヌ",
  "Roussanne": "ルーサンヌ",
  "Clairette": "クレレット",
  "Muscardin": "ミュスカルダン",
  "Counoise": "クノワーズ",
  "Bourboulenc": "ブールブーラン",
  "Picpoul": "ピクプール",
  "Tannat": "タナ",
  "Négrette": "ネグレット",
  "Fer Servadou": "フェル・セルヴァドゥ",

  // Italy: DOCG/DOC names and places
  "Brunello di Montalcino": "ブルネッロ・ディ・モンタルチーノ",
  "Vino Nobile di Montepulciano": "ヴィーノ・ノービレ・ディ・モンテプルチアーノ",
  "Amarone della Valpolicella": "アマローネ・デッラ・ヴァルポリチェッラ",
  "Recioto della Valpolicella": "レチョート・デッラ・ヴァルポリチェッラ",
  "Conegliano Valdobbiadene-Prosecco": "コネリアーノ・ヴァルドッビアデーネ・プロセッコ",
  "Colli Bolognesi Pignoletto": "コッリ・ボロニェージ・ピニョレット",
  "Colli Orientali del Friuli Picolit": "コッリ・オリエンターリ・デル・フリウリ・ピコリット",
  "Aglianico del Vulture Superiore": "アリアニコ・デル・ヴルトゥレ・スペリオーレ",
  "Cesanese del Piglio": "チェザネーゼ・デル・ピーリオ",
  "Fiano di Avellino": "フィアーノ・ディ・アヴェッリーノ",
  "Greco di Tufo": "グレーコ・ディ・トゥーフォ",
  "Vermentino di Gallura": "ヴェルメンティーノ・ディ・ガッルーラ",
  "Torgiano Rosso Riserva": "トルジャーノ・ロッソ・リゼルヴァ",
  "Primitivo di Manduria Dolce Naturale": "プリミティーヴォ・ディ・マンドゥーリア・ドルチェ・ナトゥラーレ",
  "Castel del Monte Nero di Troia Riserva": "カステル・デル・モンテ・ネーロ・ディ・トロイア・リゼルヴァ",
  "Castel del Monte Rosso Riserva": "カステル・デル・モンテ・ロッソ・リゼルヴァ",
  "Castelli di Jesi Verdicchio Riserva": "カステッリ・ディ・イエージ・ヴェルディッキオ・リゼルヴァ",
  "Verdicchio di Matelica Riserva": "ヴェルディッキオ・ディ・マテリカ・リゼルヴァ",
  "Colline Teramane Montepulciano d'Abruzzo": "コッリーネ・テラマーネ・モンテプルチアーノ・ダブルッツォ",
  "Ruchè di Castagnole Monferrato": "ルケ・ディ・カスタニョーレ・モンフェッラート",
  "Oltrepò Pavese Metodo Classico": "オルトレポ・パヴェーゼ・メトド・クラッシコ",
  "Montefalco Sagrantino": "モンテファルコ・サグランティーノ",
  "Montecucco Sangiovese": "モンテクッコ・サンジョヴェーゼ",
  "Vernaccia di San Gimignano": "ヴェルナッチャ・ディ・サン・ジミニャーノ",
  "Cerasuolo di Vittoria": "チェラスオーロ・ディ・ヴィットリア",
  "Morellino di Scansano": "モレッリーノ・ディ・スカンサーノ",
  "Romagna Albana": "ロマーニャ・アルバーナ",
  "Barbera d'Asti": "バルベーラ・ダスティ",
  "Barbera d'Alba": "バルベーラ・ダルバ",
  "Dolcetto di Ovada Superiore": "ドルチェット・ディ・オヴァーダ・スペリオーレ",
  "Dolcetto di Diano d'Alba": "ドルチェット・ディ・ディアーノ・ダルバ",
  "Sforzato di Valtellina": "スフォルツァート・ディ・ヴァルテッリーナ",
  "Valtellina Superiore": "ヴァルテッリーナ・スペリオーレ",
  "Soave Superiore": "ソアーヴェ・スペリオーレ",
  "Frascati Superiore": "フラスカーティ・スペリオーレ",
  "Recioto di Soave": "レチョート・ディ・ソアーヴェ",
  "Chianti Classico": "キアンティ・クラッシコ",
  "Chianti": "キアンティ",
  "Barolo": "バローロ",
  "Barbaresco": "バルバレスコ",
  "Franciacorta": "フランチャコルタ",
  "Asti": "アスティ",
  "Gavi": "ガヴィ",
  "Roero": "ロエロ",
  "Dogliani": "ドリアーニ",
  "Gattinara": "ガッティナーラ",
  "Ghemme": "ゲンメ",
  "Taurasi": "タウラージ",
  "Nizza": "ニッツァ",
  "Offida": "オッフィーダ",
  "Rosazzo": "ロザッツォ",
  "Ramandolo": "ラマンドロ",
  "Lison": "リゾン",
  "Cònero": "コーネロ",
  "Suvereto": "スヴェレート",
  "Bolgheri": "ボルゲリ",
  "Etna": "エトナ",
  "Marsala": "マルサーラ",
  "Orvieto": "オルヴィエート",
  "Erbaluce di Caluso": "エルバルーチェ・ディ・カルーゾ",
  "Montello Rosso": "モンテッロ・ロッソ",
  "Terre Alfieri": "テッレ・アルフィエーリ",
  "Terre Tollesi": "テッレ・トッレージ",
  "Cannellino di Frascati": "カンネッリーノ・ディ・フラスカーティ",
  "Piave Malanotte": "ピアーヴェ・マラノッテ",
  "Bagnoli Friularo": "バニョーリ・フリウラーロ",
  "Bardolino Superiore": "バルドリーノ・スペリオーレ",
  "Castel del Monte Bombino Nero": "カステル・デル・モンテ・ボンビーノ・ネーロ",
  "Elba Aleatico Passito": "エルバ・アレアティコ・パッシート",
  "Brachetto d'Acqui": "ブラケット・ダックイ",
  "Cirò Classico": "チロ・クラッシコ",
  "Moscato di Scanzo": "モスカート・ディ・スカンツォ",
  "Colli Euganei Fior d'Arancio": "コッリ・エウガネイ・フィオール・ダランチョ",
  "Valpolicella Ripasso": "ヴァルポリチェッラ・リパッソ",
  "Colli di Conegliano": "コッリ・ディ・コネリアーノ",
  "Recioto di Gambellara": "レチョート・ディ・ガンベッラーラ",
  "Vernaccia di Serrapetrona": "ヴェルナッチャ・ディ・セッラペトローナ",
  "Rosso della Val di Cornia": "ロッソ・デッラ・ヴァル・ディ・コルニア",
  "Malvasia delle Lipari": "マルヴァジア・デッレ・リーパリ",
  "Vernaccia di Oristano": "ヴェルナッチャ・ディ・オリスターノ",
  "Alta Langa": "アルタ・ランガ",
  "Asolo": "アーゾロ",
  "Carmignano": "カルミニャーノ",
  "Canelli": "カネッリ",
  "Pomino": "ポミーノ",
  "Frascati": "フラスカーティ",
  "Langhe": "ランゲ",
  "Cinque Terre": "チンクエ・テッレ",
  "Oltrepò Pavese": "オルトレポ・パヴェーゼ",
  "Castelli Romani": "カステッリ・ロマーニ",
  "Est! Est!! Est!!! di Montefiascone": "エスト・エスト・エスト・ディ・モンテフィアスコーネ",
  "Aglianico del Taburno": "アリアニコ・デル・タブルノ",
  "Sangiovese di Romagna": "サンジョヴェーゼ・ディ・ロマーニャ",
  "Colli Orientali del Friuli Refosco": "コッリ・オリエンターリ・デル・フリウリ・レフォスコ",

  // Italian grape varieties
  "Sangiovese": "サンジョヴェーゼ",
  "Nebbiolo": "ネッビオーロ",
  "Barbera": "バルベーラ",
  "Dolcetto": "ドルチェット",
  "Montepulciano": "モンテプルチアーノ",
  "Aglianico": "アリアニコ",
  "Nero d'Avola": "ネーロ・ダーヴォラ",
  "Nerello Mascalese": "ネレッロ・マスカレーゼ",
  "Corvina": "コルヴィーナ",
  "Rondinella": "ロンディネッラ",
  "Molinara": "モリナーラ",
  "Garganega": "ガルガーネガ",
  "Glera": "グレーラ",
  "Verdicchio": "ヴェルディッキオ",
  "Trebbiano": "トレッビアーノ",
  "Vermentino": "ヴェルメンティーノ",
  "Fiano": "フィアーノ",
  "Greco": "グレーコ",
  "Arneis": "アルネイス",
  "Cortese": "コルテーゼ",
  "Moscato Bianco": "モスカート・ビアンコ",
  "Primitivo": "プリミティーヴォ",
  "Negroamaro": "ネグロアマーロ",
  "Sagrantino": "サグランティーノ",
  "Cannonau": "カンノナウ",
  "Carignano": "カリニャーノ",
  "Lagrein": "ラグライン",
  "Schiava": "スキアーヴァ",
  "Teroldego": "テロルデゴ",
  "Ribolla Gialla": "リボッラ・ジャッラ",
  "Friulano": "フリウラーノ",
  "Picolit": "ピコリット",

  // Germany: regions, villages, vineyards and grape varieties
  "Hessische Bergstraße": "ヘシッシェ・ベルクシュトラーセ",
  "Saale-Unstrut": "ザーレ・ウンストルート",
  "Würzburger Stein": "ヴュルツブルガー・シュタイン",
  "Bernkasteler Doctor": "ベルンカステラー・ドクトール",
  "Wehlener Sonnenuhr": "ヴェーレナー・ゾンネンウーア",
  "Piesporter Goldtröpfchen": "ピースポーター・ゴルトトレプヒェン",
  "Niersteiner Pettenthal": "ニアシュタイナー・ペッテンタール",
  "Rüdesheimer Berg Schlossberg": "リューデスハイマー・ベルク・シュロスベルク",
  "Forster Kirchenstück": "フォルスター・キルヒェンシュテュック",
  "Scharzhofberger": "シャルツホーフベルガー",
  "Mittelrhein": "ミッテルライン",
  "Rheingau": "ラインガウ",
  "Rheinhessen": "ラインヘッセン",
  "Württemberg": "ヴュルテンベルク",
  "Franken": "フランケン",
  "Baden": "バーデン",
  "Sachsen": "ザクセン",
  "Pfalz": "ファルツ",
  "Mosel": "モーゼル",
  "Nahe": "ナーエ",
  "Ahr": "アール",
  "Nierstein": "ニアシュタイン",
  "Piesport": "ピースポート",
  "Bernkastel": "ベルンカステル",
  "Rüdesheim": "リューデスハイム",
  "Johannisberg": "ヨハニスベルク",
  "Würzburg": "ヴュルツブルク",
  "Saar": "ザール",
  "Ruwer": "ルーヴァー",
  "Müller-Thurgau": "ミュラー・トゥルガウ",
  "Spätburgunder": "シュペートブルグンダー",
  "Grauburgunder": "グラウブルグンダー",
  "Weißburgunder": "ヴァイスブルグンダー",
  "Dornfelder": "ドルンフェルダー",
  "Silvaner": "ジルヴァーナー",
  "Scheurebe": "ショイレーベ",
  "Lemberger": "レンベルガー",
  "Trollinger": "トロリンガー",
  "Portugieser": "ポルトギーザー",
  "Kerner": "ケルナー"
});

(function () {
  "use strict";

  const map = window.WINE_READINGS;
  const terms = Object.keys(map).sort((a, b) => b.length - a.length);
  const latinLetters = "A-Za-zÀ-ÖØ-öø-ÿĀ-žẀ-ỹ";
  const escapeRegExp = (value) => String(value).replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const pattern = terms.length
    ? new RegExp(`(^|[^${latinLetters}])(${terms.map(escapeRegExp).join("|")})(?![${latinLetters}])`, "gu")
    : null;

  window.WINE_READING_FORMATTER = function (value) {
    const text = String(value || "");
    if (!pattern) return text;
    return text.replace(pattern, (match, prefix, term, offset, source) => {
      const reading = map[term];
      const termEnd = offset + prefix.length + term.length;
      const tail = source.slice(termEnd).trimStart();
      if (tail.startsWith(`（${reading}）`) || tail.startsWith(`(${reading})`)) return match;
      return `${prefix}${term}（${reading}）`;
    });
  };
})();
